#!/usr/bin/env bash

set -e
echo > times.csv

root=$PWD
bench() {
  bytes=$(ifconfig | sed -En 's/RX.*bytes ([0-9]+).*/\1/p' | sort -rn | head -n1)
  \time -f "$1,%e,%M" -ao $root/times.csv "${@:2}"
  bytes2=$(ifconfig | sed -En 's/RX.*bytes ([0-9]+).*/\1/p' | sort -rn | head -n1)
  mb=$(( (bytes2-bytes) / 1000000 ))
  sed -i "\$s/\$/,$mb/" $root/times.csv
}
commit=cbae1b5
args="Mathlib.mods.\"Mathlib.Tactic.ToAdditive\" --override-input lean github:leanprover/lean4/f6cd6c0 --override-input std nale+github:leanprover/std4/5c8ff9a"
git clone https://github.com/leanprover-community/mathlib4 || true
cd mathlib4
git checkout $commit
bench "Initial build" nix-portable nix build nale+git+file:$PWD#$args
bench "No-op rebuild" nix-portable nix build nale+git+file:$PWD#$args
echo >> README.md
bench "Rebuild after unrelated change" nix-portable nix build nale+git+file:$PWD#$args
cd ..
bench "URL build" nix-portable nix build nale+github:leanprover-community/mathlib4/$commit#$args
jq -Rsn '[inputs | . / "\n" | (.[] | select(length > 0) | . / ",") as $input |
  [{"name": $input[0], "unit": "s", "value": $input[1] },
   {"name": "\($input[0]) [RX]", "unit": "MB", "value": $input[3] }]] |
  flatten' < times.csv > times.json
