#!/usr/bin/env bash

source "$(dirname "${BASH_SOURCE}")"/common.sh
args="Mathlib.mods.\"Mathlib.Tactic.ToAdditive\" --override-input lean github:leanprover/lean4/adf7438 --override-input std nale+github:leanprover/std4/5c8ff9a"

bench "Initial build" nix-portable nix build nale+git+file:$PWD#$args
bench "No-op rebuild" nix-portable nix build nale+git+file:$PWD#$args
echo >> README.md
bench "Rebuild after unrelated change" nix-portable nix build nale+git+file:$PWD#$args
bench "URL build" nix-portable nix build nale+github:leanprover-community/mathlib4/$commit#$args

toJson
