name: "CI"
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - master

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
      with:
        upstream-cache: https://lean4.cachix.org
    - name: Install Cachix
      uses: cachix/cachix-action@v12
      with:
        name: lean4
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        skipPush: true  # we push specific outputs only
    - name: Build
      id: build
      run: |
        nix flake lock --update-input lake2nix --option access-tokens github.com=${{ secrets.GITHUB_TOKEN }}  # HACK
        nix run .#nix -- build ./lake2nix -o push
        nix build .
      shell: nix run .#ciShell -- bash -euxo pipefail {0}
    - name: Push to Cachix
      run: |
        [ -z "${{ secrets.CACHIX_AUTH_TOKEN }}" ] || cachix push -j4 lean4 ./push* || true
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: nale-bin
        path: result/bin

  bench:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: nale-bin
      - name: Setup
        run: |
          chmod u+x nale-bin/nale-bin/nix-portable
          echo $PWD/nale-bin/nale-bin >> $GITHUB_PATH
          mkdir ~/.nix-portable
          echo "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}" >> ~/.nix-portable/nix.conf
          sudo apt install moreutils
      - name: Bench
        shell: bash -euxo pipefail {0}
        run: CI=1 ./script/bench |& ts -i "(%.S)]" | ts -s "[%M:%S"
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: customSmallerIsBetter
          output-file-path: times.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}

  bench-reference:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: sudo apt install moreutils
      - name: Bench
        shell: bash -euxo pipefail {0}
        run: ./script/bench-reference |& ts -i "(%.S)]" | ts -s "[%M:%S"
      - name: Store reference result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Lake Reference
          tool: customSmallerIsBetter
          output-file-path: times.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: nale-bin
      - name: Chore
        run: |
          chmod u+x nale-bin/nale-bin/nix-portable
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: nale-bin/nale-bin/nix-portable
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
